### ISSUE TITLE
linker `flip-link` not found when using target `thumbv7em-none-eabihf`

### ISSUE THREAD

**Issue by liamkinne** [knurling-rs/flip-link#81]
I believe it doesn't work with a hard-float target because it will work with the target set to `thumbv7em-none-eabi`.

Here is my `.cargo/config.toml`

```toml
[target.thumbv7em-none-eabihf]
runner = "probe-run --chip STM32F334R8Tx --connect-under-reset"
rustflags = [
  "-C", "linker=flip-link",
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=--nmagic",
  "-C", "link-arg=-Tdefmt.x",
]

[build]
target = "thumbv7em-none-eabihf"

[env]
DEFMT_LOG = "trace"

```
